version: 2.1

orbs:
  versioning: kollex/versioning@1.0.0


jobs:

  versiona:
    working_directory: ~/app1
    docker:
      - image: circleci/python:3.6-stretch
    steps:
      # Move the repository code to our home directory in the CircleCI build
      #- checkout
      - attach_workspace:
          at: .
      # Add deployment key fingerprint for CircleCI to use for a push
      - add_ssh_keys:
          fingerprints:
            - "1f:cc:12:f5:25:e7:cc:3d:fb:3e:1e:f9:44:47:29:b3"
            #- "0d:c6:2b:93:38:34:5b:88:3f:2e:5c:c3:6f:46:a4:a5"
      - versioning/define_version
      - versioning/print_version
      - versioning/print_docker_tag 
      - run: echo $DOCKER_TAG
      - run: echo $VERSION 
      - run: ls -l 
      - run: git config user.email "$GIT_CORREO"
      - run: git config user.name "$GIT_USER"
      - run: git checkout main
      - run: |
             sed -e "s/image: $DOCKERHUB_USERNAME\/ms:.*/image: $DOCKERHUB_USERNAME\/ms:$DOCKER_TAG/g" -i app/deployment.yaml
      - run: cat app/deployment.yaml
      - run: git add .
      - run: git commit -m "circleci $DOCKER_TAG"      
      - run: git push

  build:
    working_directory: ~/app1
    machine:
      image: ubuntu-2204:2022.04.2
    steps:
    - attach_workspace:
        at: .
    - run:
        name: Visualizacion del jar
        command: ls -l ~/app1/target/
    - versioning/define_version        
    - run: 
        name: Publish Docker Image to Docker Hub
        command: |
          echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
          ##docker build -t $IMAGE_NAME:$DOCKER_TAG .
          docker build -t $DOCKERHUB_USERNAME/ms:$DOCKER_TAG .
          docker push $DOCKERHUB_USERNAME/ms:$DOCKER_TAG        

  test:
    working_directory: ~/app1
    docker:
      - image: maven 
    steps: 
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          # Si hay un cambio en las dependencias en proyectos java siempre van en el pom
          - v1-dependencies-
      - run: 
          name: generacion 
          command: mvn clean package
      - run: 
          name: test 
          command: mvn test
      - run:
          name: Analyze on SonarCloud
          command: mvn verify sonar:sonar -Dsonar.projectKey=cjcuesta_cici-java          
      - run:
          name: Visualizacion del jar
          command: ls -l ~/app1/target/
      - persist_to_workspace:
          root: .
          paths: ./


workflows:
  my-workflow:
    when: << pipeline.git.tag >>  
    jobs:
      - test:
          context: SonarCloud 
          filters:
            tags:
              only: /.*/
      - build:
          requires:
            - test 
          filters:
            tags:
              only: /.*/
      - versiona:
          requires:
            - build
          filters:
            tags:
              only: /.*/


