version: 2.1


jobs:
  build:
    working_directory: ~/app
    machine:
      image: ubuntu-2204:2022.04.2
    environment: 
      IMAGE_NAME: cjcuesta/ms
    steps:
    - attach_workspace:
        at: .
    - run:
        name: Visualizacion del jar
        command: ls -l ~/app/
    - run: 
        name: Publish Docker Image to Docker Hub
        command: |
          echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
          docker build -t $IMAGE_NAME:v2 .
          docker push $IMAGE_NAME:v2        

  test:
    working_directory: ~/app
    docker:
      - image: maven 
    steps: 
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: 
          name: generacion 
          command: mvn clean package
      - run: 
          name: test 
          command: mvn test
      - run:
          name: Analyze on SonarCloud
          command: mvn verify sonar:sonar -Dsonar.projectKey=cjcuesta_cici-java          
      - run:
          name: Visualizacion del jar
          command: ls -l ~/app/target/
      - run:
          name: prueba GIT
          command: |
            echo "hola mundo" > notas.txt
            git config user.name "cjcuesta"
            echo "hola 1"
            git config user.email "cjcuesta@gmail.com"
            echo "hola 2"
            git add .
            git commit -m "Nuevo elemento"
            git push
      - persist_to_workspace:
          root: .
          paths: ./


workflows:
  my-workflow:
    jobs:
      - test:
          context: SonarCloud
      - build:
          requires:
            - test 

